# Copyright (c) 2020 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: sqs-twilio
  name: sqs-twilio
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: events-aws

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: transform-sqs
            
    - object:
        apiVersion: sources.knative.dev/v1alpha2
        kind: ContainerSource
        metadata:
          name: aws-sqs
        spec:
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-aws
          template:
            metadata:
              creationTimestamp: null
            spec:
              containers:
              - env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: K_LOGGING_CONFIG
                  value: '{"level":"info"}'
                - name: K_METRICS_CONFIG
                  value: '{"domain":"triggermesh.io/sources","component":"awssqssource","configMap":{}}'
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: aws_access_key_id
                      name: awscreds
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: aws_secret_access_key
                      name: awscreds
                - name: ARN
                  value: arn:aws:sqs:us-east-1:587264368683:triggermesh
                image: gcr.io/triggermesh/awssqssource:latest
                name: source
                resources: {}

    - object:
        apiVersion: messaging.knative.dev/v1beta1
        kind: Subscription
        metadata:
          name: event-twilio
        spec:
          channel:
            apiVersion: messaging.knative.dev/v1beta1
            kind: InMemoryChannel
            name: events-aws-kne-trigger
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: trans-twilio
          reply:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: transform-sqs

    - object:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        metadata:
          name: trans-twilio
          labels:
            serving.knative.dev/visibility: cluster-local
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/triggermesh/transtwilio:v0.0.13

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          labels:
            eventing.knative.dev/broker: text-message-hub
          name: sendme-twilio
        spec:
          broker: transform-sqs
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: TwilioTarget
              name: twilio-sqs-sms

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: TwilioTarget
        metadata:
          name: twilio-sqs-sms
        spec:
          defaultPhoneTo: "+19998887777"
          defaultPhoneFrom: "+125666666"
          sid:
            secretKeyRef:
              name: twilio
              key: sid
          token:
            secretKeyRef:
              name: twilio
              key: token


