apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: oci-datadog
  name: oci-datadog
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: oci-datadog

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: oracle-source
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/triggermesh/oracle-source:latest
                env:
                  - name: PSK
                    valueFrom:
                      secretKeyRef:
                        name: oraclesourcepsk
                        key: psk
    # Transformation Service
    - object:
        apiVersion: flow.triggermesh.io/v1alpha1
        kind: Transformation
        metadata:
          name: transform-02
        spec:
          context:
          - operation: add
            paths:
            - key: type 
              value: com.oracle.cloud.monitoring.metric
          data:
          - operation: store
            paths: 
            - key: $displayName
              value: metadata.displayName
            - key: $unit
              value: metadata.unit
            - key: $resourceGroup
              value: Dimensions.resourceDisplayName
          - operation: delete
            paths:
            - key:
          - operation: add
            paths:
            - key: displayname
              value: '$displayName'
            - key: unit
              value: '$unit'
            - key: resourcegroup
              value: '$resourceGroup'
   # Transformation Trigger : Subscribes the transformation service to recieve events from the 'event-broker'
   - object:
    apiVersion: eventing.knative.dev/v1
    kind: Trigger
    metadata:
      name: transform-trigger
    spec:
      broker: oci-datadog
      filter:
        attributes:
          type: com.oracle.cloud.monitoring
      subscriber:
        ref:
          apiVersion: flow.triggermesh.io/v1alpha1
          kind: Transformation
          name: transform-0
    # Event Target
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: DataDogTarget
        metadata:
         name: datadog
        spec:
          agent: "10.1.67.75"
    # Event Target Trigger
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: datadog
        spec:
          broker: oci-datadog
          filter:
            attributes:
              type: io.triggermesh.oracle.db.oci.metric
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: DataDogTarget
              name: datadog
        
