
apiVersion: v1
kind: Secret
metadata:
  name: twiliosecret
type: Opaque
stringData:
  sid: ''
  token: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: githubsecret
type: Opaque
stringData:
  accessToken: ''
  secretToken: ''



