# Copyright (c) 2020 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Replace the apiPassphrase, apiFingerprint, and apiKey with the appropriate
# values for interacting with the Oracle Cloud REST API

apiVersion: v1
kind: Secret
metadata:
  name: oraclecreds
type: Opaque
stringData:
  apiPassphrase: 'ENTER_PASSPHRASE_HERE'
  apiKeyFingerprint: 'ENTER_PUBLIC_KEY_FINGERPRINT_HERE'
  apiKey: |-
    -----BEGIN RSA PRIVATE KEY-----
    ENTER_PRIVATE_KEY_HERE
    -----END RSA PRIVATE KEY-----

---

apiVersion: v1
kind: Secret
metadata:
  name: ddapitoken
type: Opaque
stringData:
  apiKey: __API_KEY__ 