apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: oci-datadog
  name: oci-datadog
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: oci-datadog

    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: OCIMetricsSource
        metadata:
          name: metrics-test
        spec:
          # required to interact with the Oracle Cloud API
          oracleApiPrivateKey:
            secretKeyRef:
              name: oraclecreds
              key: apiKey
          oracleApiPrivateKeyPassphrase:
            secretKeyRef:
              name: oraclecreds
              key: apiPassphrase
          oracleApiPrivateKeyFingerprint:
            secretKeyRef:
              name: oraclecreds
              key: apiKeyFingerprint
              oracleTenancy: ocid1.tenancy.oc1..aaaaaaaaswreplaceme
              oracleUser: ocid1.user.oc1..aaaaaaaaqlocaluser
          oracleRegion: us-ashburn-1
          # required to enable metrics
          metricsNamespace: oci_computeagent
          metricsQuery: NetworksBytesOut[1m].mean()
          # optional polling frequency. default to 5m
          metricsPollingFrequency: 10m
          sink:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: event-display
    # Transformation Service
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
            name: oci-datadog
        spec:
            template:
                spec:
                    containers:
                    - image: gcr.io/neffdev/oci-trans:latest
    # Transformation Trigger : Subscribes the transformation service to recieve events from the 'event-broker'
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: trans-datadog
        spec:
          broker: oci-datadog
          filter:
            attributes:
              type: com.oracle.cloud.monitoring
          subscriber:
            ref:
              apiVersion: flow.triggermesh.io/v1alpha1
              kind: Transformation
              name: transform-0
    # Event Target
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: DataDogTarget
        metadata:
         name: datadog
        spec:
          agent: "10.1.67.54"
    # Event Target Trigger
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: datadog
        spec:
          broker: oci-datadog
          filter:
            attributes:
              type: io.triggermesh.datadog.metric.aggregated
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: DataDogTarget
              name: datadog
         
