apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
    name: trans-datadog
spec:
    template:
        spec:
            containers:
            - image: gcr.io/triggermesh/transdatadog:latest

