apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: uipath-sendgrid
  name: uipath-sendgrid
spec:
  components:

    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name: &broker salesforce-in

    - object:
        apiVersion: flow.triggermesh.io/v1alpha1
        kind: Transformation
        metadata:
          name: sf-ui
        spec:
          context:
          - operation: add
            paths:
            - key: type 
              value: io.triggermesh.uipath.job
          data:
          - operation: store
            paths: 
            - key: $AccountName
              value: payload.AccountName__c
            - key: $Email
              value: payload.Email__c
            - key: $Address
              value: payload.FullAddress__c
          - operation: delete
            paths:
            - key:
          - operation: add
            paths:
            - key: inputArgs
              value: '"Email__c" : "$Email", "FullAddress__c" : "$Address","AccountName__c": "$AccountName"'

    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: sf-ui
        spec:
          broker: *broker 
          filter:
            attributes:
              type: com.salesforce.stream.message
          subscriber:
            ref:
              apiVersion: flow.triggermesh.io/v1alpha1
              kind: Transformation
              name: sf-ui
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: UiPathTarget
        metadata:
          name: uipathtwo
        spec:
           robotName: pfml1
           processName: ExcelEntry_plz
           tenantName: midiDefault
           accountLogicalName: midi
           clientID: 8DEv1AMNXczW3y4U15LL3jYf62jK93n5
           organizationUnitID: "785170"
           #inputArgs: "ENV_UserName:\"Hello bob\""
           userKey:
             secretKeyRef:
               name: uipath
               key: userKey


    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: uipath
        spec:
          broker: *broker
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: UiPathTarget
              name: uipath
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name:  &repBroker response-events
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: HTTPSource
        metadata:
            name: uipath
        spec:
            eventSource: uipath
            eventType: io.triggermesh.uipath
            sink:
                ref:
                    apiVersion: eventing.knative.dev/v1
                    kind: Broker
                    name: *repBroker
    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: ui-sendgrid-trans
          labels:
            serving.knative.dev/visibility: cluster-local
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/neffdev/ui-sendgrid:latest
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: ui-sendgrid-trans
        spec:
          broker: *repBroker
          filter:
            attributes:
              type: io.triggermesh.uipath
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: ui-sendgrid-trans
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: SendGridTarget
        metadata:
          name: sendgrid
        spec:
          defaultFromName: jeff
          defaultFromEmail: dev@triggermesh.com
          defaultSubject: Your Triggermesh Invoice Is Now Avalible
          apiKey:
            secretKeyRef:
              name: sendgrid
              key: apiKey
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          labels:
          name: sendgrid
        spec:
          broker: *repBroker
          filter:
            attributes:
              type: io.triggermesh.sendgrid.email.send
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: SendGridTarget
              name: sendgrid
 