apiVersion: v1
kind: Secret
metadata:
  name: sendgrid
type: Opaque
stringData:
  apiKey: ''  # Update this value with a valid Sendgrid API key

---

apiVersion: v1
kind: Secret
metadata:
  name: zendesk-api
type: Opaque
stringData:
  token:  '<ZENDESK API TOKEN>'
  webhookPassword: '<ARBITRARY PASSWORD FOR BASIC AUTH>'