apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: slack-slack
  name: slack-slack
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: slack
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: transform-slack

    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: SlackSource
        metadata:
          name: triggermesh-bot
        spec:
          slackToken:
            secretKeyRef:
              name: slacksource
              key: token
          threadiness: 1
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: slack

    - object:
        apiVersion: messaging.knative.dev/v1beta1
        kind: Subscription
        metadata:
          name: slack-translate
        spec:
          channel:
            apiVersion: messaging.knative.dev/v1beta1
            kind: InMemoryChannel
            name: slack-kne-trigger
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: googletranslate
          reply:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: transform-slack

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: SlackTarget
        metadata:
          name: triggermesh-bot
        spec:
          defaultChannel: "tmspanish"
          slackToken:
            secretKeyRef:
              name: slacktarget
              key: SLACK_TOKEN
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: slack-slack-trigger
        spec:
          broker: transform-slack
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: SlackTarget
              name: triggermesh-bot
