# This is an EXAMPLE Bridge. Before deploying it, replace all of the placeholder values with valid data. 
apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  name: http-sendgrid
  annotations:
    bridges.triggermesh.io/name: http-sendgrid
spec:
  components:

    # Event broker
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name: events
    # Event source
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: HTTPSource
        metadata:
          name: httpsource-test
        spec:
          eventType: com.zendesk.ticket.created
          eventSource: zengrid
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1
              kind: Broker
              name: events
    # Transformation Trigger 
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: transform-trigger
        spec:
          broker: events
          filter:
            attributes:
              type: com.zendesk.ticket.created
          subscriber:
            ref:
              apiVersion: flow.triggermesh.io/v1alpha1
              kind: Transformation
              name: transform-0
    # Transformation Service
    - object:
        apiVersion: flow.triggermesh.io/v1alpha1
        kind: Transformation
        metadata:
          name: transform-0
        spec:
          context:
          - operation: add
            paths:
            - key: type 
              value: io.triggermesh.sendgrid.send
          data:
          - operation: store
            paths: 
            - key: $url
              value: ticket.url
            - key: $author
              value: current_user.email
            - key: $description
              value: ticket.description
          - operation: delete
            paths:
            - key:
          - operation: add
            paths:
            - key: message
              value: '$author created a new Zendesk support Ticket: $url Description: $description'
    # Event Trigger
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: tmsg
        spec:
          broker: events
          filter:
            attributes:
              type: io.triggermesh.sendgrid.send
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: SendGridTarget
              name: tmsg
    # Event Target
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: SendGridTarget
        metadata:
          name: tmsg
        spec:
          defaultFromName: foo
          defaultFromEmail: foo@triggermesh.com
          defaultToName: bar
          defaultToEmail: bar@gmail.com
          defaultSubject: New Zendesk Ticket 
          apiKey:
            secretKeyRef:
              name: sendgrid
              key: apiKey

