# This is an EXAMPLE Bridge. Before deploying it, replace all of the placeholder values with valid data. 
---
apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  name: &bridgename zendesk-comprehend-zendesk
  annotations:
    bridges.triggermesh.io/name: *bridgename
spec:
  components:

    # Event broker
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: &brokername events

    # Event source
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: ZendeskSource
        metadata:
          name: zendesk
        spec:
          email: &email '<ZENDESK ACCOUNT USER EMAIL>'
          subdomain: &subdomain '<ZENDESK TENANT SUBDOMAIN>'
          token:
            secretKeyRef:
              name: zendesk-api
              key: token
          webhookUsername: '<SOME ARBITRARY USERNAME>'
          webhookPassword:
            secretKeyRef:
              name: zendesk-api
              key: webhookPassword
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: *brokername

    # Transformation service
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: &transformname transform-sentiment-tag
        spec:
          broker: *brokername
          filter:
            attributes:
              type: com.zendesk.ticket.created
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: *transformname
    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: *transformname
          labels:
            serving.knative.dev/visibility: cluster-local
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/triggermesh/bridge-examples/zendesk-zendesk-transform-sentiment-tag
                env:
                  - name: LANGUAGE
                    value: en 
                  - name: AWS_REGION
                    value: '<AWS REGION>'
                envFrom:
                  - secretRef:
                    name: awscomprehend
                    optional: false 

    # Event target 
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: &targetname zendesk
        spec:
          broker: *brokername
          filter:
            attributes:
              type: com.zendesk.tag.create
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ZendeskTarget
              name: *targetname
    - object:
         apiVersion: targets.triggermesh.io/v1alpha1
         kind: ZendeskTarget
         metadata:
          name: *targetname
         spec:
           email: *email
           subdomain: *subdomain
           token:
            secretKeyRef:
              name: zendesk-api
              key: token
